language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - env
  - docker pull selenium/standalone-chrome-debug:2.45.0
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - export DOCKER_TLS_VERIFY=0
  - env
script:
  - mvn test

cache:
  directories:
    - '$HOME/.m2/repository'